"""room_beds

Revision ID: 06f4e101d437
Revises: 2bd1d80bc63d
Create Date: 2026-05-16 16:59:32.175063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06f4e101d437'
down_revision: Union[str, None] = '2bd1d80bc63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('beds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'beds')
    # ### end Alembic commands ###
