"""room_floor

Revision ID: 2bd1d80bc63d
Revises: add_hotel_slug
Create Date: 2026-05-16 16:28:18.731138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bd1d80bc63d'
down_revision: Union[str, None] = 'add_hotel_slug'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'floor')
    # ### end Alembic commands ###
