"""hotel_services

Revision ID: e7a75efd5fd7
Revises: a1add_admin_role
Create Date: 2026-05-16 14:59:54.298758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7a75efd5fd7'
down_revision: Union[str, None] = 'a1add_admin_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=256), nullable=False),
    sa.Column('name_ky', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('price_kgs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_services_hotel_id'), 'hotel_services', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_services_hotel_id'), table_name='hotel_services')
    op.drop_table('hotel_services')
    # ### end Alembic commands ###
